flasknotebook/notes/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class NoteForm(FlaskForm):
    title = StringField('Tytuł', validators=[DataRequired()])
    content = TextAreaField('Treść', validators=[DataRequired()])
    submit = SubmitField('Zapisz')

flasknotebook/notes/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flasknotebook import db
from flasknotebook.models import Note
from flasknotebook.notes.forms import NoteForm

notes = Blueprint('notes', __name__)

@notes.route("/note/new", methods=['GET', 'POST'])
@login_required
def new_note():
    form = NoteForm()
    if form.validate_on_submit():
        note = Note(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(note)
        db.session.commit()
        flash('Twoja notatka została zapisana!', 'succes')
        return redirect(url_for('users.user_notes', username=note.author.username))
    return render_template('create_note.html', title='Nowa notatka', form=form, legend='Nowa notatka')

@notes.route("/note/<int:note_id>")
def note(note_id):
    note = Note.query.get_or_404(note_id)
    return render_template('note.html', title=note.title, note=note)

@notes.route("/note/<int:note_id>/update", methods=['GET', 'POST'])
@login_required
def update_note(note_id):
    note = Note.query.get_or_404(note_id)
    if note.author != current_user:
        abort(403)
    form = NoteForm()
    if form.validate_on_submit():
        note.title = form.title.data
        note.content = form.content.data
        db.session.commit()
        flash('Twoja notatka została zaktualizowana!', 'success')
        return redirect(url_for('notes.note', note_id=note.id))
    elif request.method == 'GET':
        form.title.data = note.title
        form.content.data = note.content
    return render_template('create_note.html', title='Zaktualizuj notatkę', form=form, legend='Zaktualizuj notatkę')

@notes.route("/note/<int:note_id>/delete", methods=['POST'])
@login_required
def delete_note(note_id):
    note = Note.query.get_or_404(note_id)
    if note.author != current_user:
        abort(403)
    db.session.delete(note)
    db.session.commit()
    flash('Twoja notatka została usunięta!', 'succes')
    return redirect(url_for('main.home'))

flasknotebook/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flasknotebook import db, bcrypt
from flasknotebook.models import User, Note
from flasknotebook.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from flasknotebook.users.utils import save_picture

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Twoje konto zostało utworzone! Możesz teraz się zalogować.', 'succes')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Zarejestruj się', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('users.user_notes', username=current_user.username))
        else:
            flash('Logowanie nie powiodło się. Proszę sprawdzić email lub hasło.', 'danger')
    return render_template('login.html', title='Zaloguj się', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Twoje konto zostało zaktualizowane!', 'succes')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pictures/' + current_user.image_file)
    return render_template('account.html', title='Konto', image_file=image_file, form=form)

@users.route("/user/<string:username>")
def user_notes(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    notes = Note.query.filter_by(author=user)\
        .order_by(Note.date_noted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_notes.html', notes=notes, user=user)

flasknotebook/templates/account.html
{% extends "layout.html" %}
{% block content %}
<head>
  <meta charset="UTF-8">
</head>
  <div class="content-section" style="background-color: #F0F8FF;">
    <div class="media">
      <img class="rounded account-img" src="{{ image_file }}">
      <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
      </div>
    </div>
      <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Informacje o koncie</legend>
          <div class="form-group">
            {{ form.username.label(class="form-control-label") }}
            {% if form.username.errors %}
              {{ form.username(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.username.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.username(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
              {{ form.email(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.picture.label() }}
            {{ form.picture(class="form-control-file") }}
            {% if form.picture.errors %}
              {% for error in form.email.errors %}
                <span class="text-danger">{{ error }}</span></br>
              {% endfor %}
            {% endif %}
          </div>
        </fieldset>
        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
        </div>
      </form>
  </div>
{% endblock content %}

flasknotebook/templates/create_note.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section" style="background-color: #F0F8FF;">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">{{ legend }}</legend>
      <div class="form-group">
        {{ form.title.label(class="form-control-label") }}
        {% if form.title.errors %}
          {{ form.title(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.title.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.title(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.content.label(class="form-control-label") }}
        {% if form.content.errors %}
          {{ form.content(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.content.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.content(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}

flasknotebook/templates/home.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section" style="background-color: #F0F8FF;">
    <h1>O stronie</h1>
    <p>Witaj w mojej aplikacji notatnika! Zapraszam do utworzenia konta, dzięki któremu będziesz mógł dodawać nowe notatki!</p>
</div>
{% endblock content %}

flasknotebook/templates/layout.html
<!DOCTYPE html>
<html>
 <head>
   <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

   <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">

  {% if title %}
    <title>My Notebook - {{ title }}</title>
  {% else %}
    <title>My Notebook</title>
  {% endif %}
 </head>
 <body>
   {% if current_user.is_authenticated %}
   <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #2F4F4F;">
      <div class="container">
        <a class="navbar-brand mr-4" href="{{ url_for('users.user_notes', username=current_user.username) }}">My Notebook</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
              <a class="nav-item nav-link" href="{{ url_for('notes.new_note') }}">Nowa notatka</a>
              <a class="nav-item nav-link" href="{{ url_for('users.user_notes', username=current_user.username) }}">Moje notatki</a>
              <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Konto</a>
              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Wyloguj się</a>
          </div>
        </div>
      </div>
    </nav>
  </header>
  {% else %}
  <header class="site-header">
   <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #2F4F4F;">
     <div class="container">
       <a class="navbar-brand mr-4" href="/">My Notebook</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarToggle">
         <div class="navbar-nav mr-auto">
         </div>
         <!-- Navbar Right Side -->
         <div class="navbar-nav">
           <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Zaloguj się</a>
           <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Zarejestruj się</a>
         </div>
       </div>
     </div>
   </nav>
 </header>
 {% endif %}
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
      </div>
  </main>

   <!-- Optional JavaScript -->
   <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 </body>
 </html>

flasknotebook/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section" style="background-color: #F0F8FF;">
      <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Zaloguj się</legend>
          <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
              {{ form.email(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors %}
              {{ form.password(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.password.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.password(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-check">
            {{ form.remember(class="form-check-input") }}
            {{ form.remember.label(class="form-check-label") }}
          </div>
        </fieldset>
        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
        </div>
      </form>
    </div>
    <div class="border-top pt-3">
      <small class="text-muted">
        Nie posiadasz konta? <a class="ml-2" href="{{ url_for('users.register') }}">Zarejestruj się</a>
      </small>
    </div>
{% endblock content %}

flasknotebook/templates/note.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section" style="background-color: #F0F8FF;">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pictures/' + note.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_notes', username=note.author.username) }}">{{ note.author.username }}</a>
        <small class="text-muted">{{ note.date_noted.strftime('%Y-%m-%d') }}</small>
        {% if note.author == current_user %}
          <div>
              <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('notes.update_note', note_id=note.id) }}">Zaktualizuj</a>
              <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Usuń</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ note.title }}</h2>
      <p class="article-content">{{ note.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Usunąć notatke?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Zamknij</button>
          <form action="{{ url_for('notes.delete_note', note_id=note.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Usuń">
          </form>
        </div>
      </div>
    </div>
  </div>{% endblock content %}

flasknotebook/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section" style="background-color: #F0F8FF;">
      <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Dołącz do nas już dziś!</legend>
          <div class="form-group">
            {{ form.username.label(class="form-control-label") }}

            {% if form.username.errors %}
              {{ form.username(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.username.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.username(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
              {{ form.email(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors %}
              {{ form.password(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.password.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.password(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.confirm_password.label(class="form-control-label") }}
            {% if form.confirm_password.errors %}
              {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.confirm_password.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.confirm_password(class="form-control form-control-lg") }}
            {% endif %}
          </div>
        </fieldset>
        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
        </div>
      </form>
    </div>
    <div class="border-top pt-3">
      <small class="text-muted">
        Posiadasz już konto? <a class="ml-2" href="{{ url_for('users.login') }}">Zaloguj się</a>
      </small>
    </div>
{% endblock content %}

flasknotebook/templates/user_notes.html
{% extends "layout.html" %}
{% block content %}
  <h1 class="mb-3">Moje notatki ({{ notes.total }})</h1>
  {% for note in notes.items %}
    <article class="media content-section" style="background-color: #F0F8FF;">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pictures/' + note.author.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_notes', username=note.author.username) }}">{{ note.author.username }}</a>
          <small class="text-muted">{{ note.date_noted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('notes.note', note_id=note.id) }}">{{ note.title }}</a></h2>
        <p class="article-content">{{ note.content }}</p>
      </div>
    </article>
  {% endfor %}
  {% for page_num in notes.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if notes.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('users.user_notes', username=user.username, page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_notes', username=user.username, page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
{% endblock content %}